server:
  port: 8763

spring:
  application:
    name: dropstat-api-gateway
  cloud:
    gateway:
      routes:     
        - id: dropstat-user-api
          uri: lb://DROPSTAT-USER-API
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL do Eureka Server
  instance:
    prefer-ip-address: true