server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: ${APPLICATION_NAME:dropstat-batch}
  datasource:
    username: root
    password: 12345
    hikari:
      maxLifetime: '600000'
      minimumIdle: '10'
      poolName: ${spring.application.name}
      idleTimeout: '300000'
      maximumPoolSize: '50'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dropstat-db?useSSL=false&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect

  quartz:
    jdbc:
      initialize-schema: always
      schema: classpath:db/quartz/tables_sqlite.sql
    properties:
      org:
        quartz:
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            useProperties: 'false'
            isClustered: 'true'
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
          scheduler:
            instanceId: AUTO
            instanceName: dropdstat-cluster
    job-store-type: jdbc
  flyway:
    enabled: true
    locations: classpath:db/migration  # Localização dos scripts de migração
    baseline-on-migrate: true
sendgrid:
  api:
    key: ${{ secrets.SEND_GRID_API_KEY }}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL do Eureka Server
  instance:
    prefer-ip-address: true